set -g mouse on
set -g @continuum-restore 'on'
set-option -g status-position top
set-option -g renumber-windows on

set -g default-terminal "tmux-256color"

set -g xterm-keys on
set -s extended-keys always
set -g focus-events on

set -g terminal-features[0] "xterm*:RGB"
set -g terminal-features[1] "xterm*:extkeys"
set -g terminal-features[2] "xterm*:clipboard"
set -g terminal-features[3] "xterm*:ccolour"
set -g terminal-features[4] "xterm*:cstyle"
set -g terminal-features[5] "xterm*:focus"
set -g terminal-features[6] "xterm*:title"
set -g terminal-features[7] "tmux*:RGB"
set -g terminal-features[8] "tmux*:extkeys"

set -g terminal-overrides[0] "xterm*:Tc"
set -g terminal-overrides[1] "tmux*:Tc"

unbind C-b
unbind -n C-j

set -g prefix C-a
bind C-a send-prefix

set -gq allow-passthrough on
set -g visual-activity off

# bind -n C-M-h previous-window
# bind -n C-M-l next-window
bind -n M-h previous-window
bind -n M-l next-window

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set-option -g status-style fg=white,bg=colour234

# active window
# set-window-option -g window-status-current-style fg=colour231,bg=default
set-window-option -g window-status-current-style fg=colour46,bg=default

# inactive windows
set-window-option -g window-status-style fg=colour244,bg=default